### ISSUE TITLE
ImageLoader.js:316 - Uncaught TypeError: this._elements[i].getAttribute is not a function

### ISSUE THREAD

**Issue by calebmichaelsanchez** [ProperJS/ImageLoader#2]
Using this package for a small express site I'm building. 

Js is being compiled with webpack, and I am just using the example code you have in the readme. Not sure why this error is coming up. I am using jade if that makes a difference. 

Thanks for making this package! I'd love to help in any way possible.

**Comment by kitajchuk** [comment]
@calebmichaelsanchez looks like you may have a `null` element in your list? How are you querying the DOM?

**Comment by calebmichaelsanchez** [comment]
I've just given all of the img's the same class and passed that class to the elements option. 

```
  var ImageLoader = require( "properjs-imageloader" );

  var onCheckImage = function ( el ) {
      var bounds = el.getBoundingClientRect();

      return ( bounds.top < window.innerHeight && bounds.bottom > 0 );
  };

  var imgLoader = new ImageLoader({
      elements: ".js-lazy-image",
      property: "data-img-src",
      executor: onCheckImage
  });
```

This is all I've got.

**Comment by calebmichaelsanchez** [comment]
I didn't quite realize I should pass an array of the elements.

Added this to my code and now it's up and running. 

```
var galleryImages = document.querySelectorAll(".gallery__item");
var galleryArray = [...galleryImages];

var imgLoader = new ImageLoader({
      elements: galleryArray,
      property: "data-img-src",
      executor: onCheckImage
});
```
